apiVersion: v1
kind: Service
metadata:
  name: shopping-site-cluster-svc
spec:
  type: ClusterIP
  selector:
    app: shopping-app-frontend
  ports:
    - port: 80
      targetport: 3000
      nodePort: 30002
